application:
  security:
    secret: HelloWorld
    expirationTime: 864000000
    tokenPrefix: 'Bearer '
    headerString: Authorization
    signUpUrl: /users/sign-up

    
spring:
  main:    lazy-initialization: false