version: '3.1'

services:
  springboot:
    build: .
    restart: always
    container_name: app
    ports:
      - 8081:8080
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: app-mongo
#    ports:  # for demo/debug purpose only
#      - 27018:27017
    volumes:
      - $HOME/data/app-mongo-data:/data/db
      - $HOME/data/app-mongo-bkp:/data/bkp
    restart: always