version: "2"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    environment:
      - NODE_ENV=prod
      - MONGO_DB_URL=MONGO_DB_URL=mongodb://mongo:27017/test
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"